[project]
name = "sync-clipboard"
version = "0.1.0"
description = "Synchronizing the clipboard between different OS via WebSocket"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "websockets>=10.0",
    "click>=8.0",
    "pyperclip>=1.8",
    "customtkinter>=5.2.2",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.17.0",
]
